services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./ha_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: America/New_York
    devices:
      - /dev/serial/by-id/usb-Nabu_Casa_ZBT-2_1CDBD45E756C-if00 -> ../../ttyACM0 
