services:
  faster-whisper:
    image: lscr.io/linuxserver/faster-whisper:latest
    container_name: faster-whisper
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DEBUG= #optional
      - LOCAL_ONLY= #optional
      - WHISPER_BEAM=1 #optional
      - WHISPER_LANG=auto #optional
      - WHISPER_MODEL=auto #optional
    volumes:
      - whisper-models-linux:/share/whisper
      - whisper-data-linux:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped

  wyoming-piper:
    image: rhasspy/wyoming-piper
    container_name: wyoming-piper
    network_mode: host
    volumes:
      - piper-models:/data
    command: --voice en_US-hfc_male-medium
    restart: unless-stopped




volumes:
  whisper-models-linux:
  whisper-data-linux:
  piper-models:
